spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: test-group
      auto-offset-reset: earliest
      enable-auto-commit: false
      properties:
#        добавил cooperative sticky assignor
        partition.assignment.strategy: org.apache.kafka.clients.consumer.CooperativeStickyAssignor
        max.poll.interval.ms: 5000
        max.poll.records: 1
    listener:
      ack-mode: manual_immediate
      concurrency: 3